Document: ktomgirl
Title: Debian ktomgirl Manual
Author: <insert document author here>
Abstract: This manual describes what ktomgirl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ktomgirl/ktomgirl.sgml.gz

Format: postscript
Files: /usr/share/doc/ktomgirl/ktomgirl.ps.gz

Format: text
Files: /usr/share/doc/ktomgirl/ktomgirl.text.gz

Format: HTML
Index: /usr/share/doc/ktomgirl/html/index.html
Files: /usr/share/doc/ktomgirl/html/*.html
